### ISSUE TITLE
The mode toggle renders the incorrect icon on initial load

### ISSUE THREAD

**Issue by devdutt10** [shadcn/next-contentlayer#2]
When the app first launches, it uses the light theme but renders the sun icon. After it is toggled once, it renders the appropriate icon based on the current theme. This also results in a warning in the DevTools console.

![Screenshot 2023-04-30 at 11 22 50 AM](https://user-images.githubusercontent.com/915813/235367361-aff774cf-ba30-4daa-ad79-af73cea1b32e.png)

**Comment by Hubgov54** [comment]
Okay I can fixed it sir . Send me your WhatsApp or telegram number so I can
text you and fixed it sir
