### ISSUE TITLE
Viewing on mobile was cutting off , left & right sides

### ISSUE THREAD

**Issue by theapplegates** [shadcn/next-contentlayer#4]
I am not sure how to make a pull request but I fixed the cutting off the left and right side when viewing on a cell phone.

I added this to `globals.css`
```
@media only screen and (max-width: 767px) {
	body {
		padding-left: 20px;
		padding-right: 20px;
	}
}

```
Now the site is fixed for mobile/cell phones.

Paul

**Comment by theapplegates** [comment]
This was also my first time using Chat-GPT to solve a problem.
<img width="793" alt="Screen Shot 2023-05-05 at 6 35 40 AM" src="https://user-images.githubusercontent.com/27178137/236436418-19321afb-b2e2-4e03-9990-b864065ed1d9.png">

**Comment by shadcn** [comment]
This is awesome. I think we can also do it with Tailwind CSS classes. Let me see if I can add the fix for it.

Thanks for your help Paul! Appreciate it.

**Comment by shadcn** [comment]
Done. Thank you.

**Comment by theapplegates** [comment]
Thanks. I appreciate you making it.

**Comment by Hubgov54** [comment]
Okay I can fixed it sir . Send me your WhatsApp or telegram number so I can
text you and fixed it sir
